// Ergonomic wrappers over the GENERATED IPC client (`src/bindings.ts`).
//
// hard rule 2 / D17: types and the client are generated by tauri-specta, never
// hand-written. The generated `commands.*` return a typed `Result<T, AppError>`;
// these thin wrappers unwrap it to the throwing `Promise<T>` contract the UI
// already uses, and re-export the generated types so the rest of the app imports
// them from one place.
import { commands } from '../bindings';
import type {
  ActivityLog,
  AppError,
  Context,
  DayView,
  Exclusion,
  Result,
  Rule,
  Setting,
  TimelineView,
  WatcherStatus,
  WeekView,
} from '../bindings';

export type {
  ActivityLog,
  AppError,
  Context,
  ContextRun,
  ContextSlice,
  DaySlice,
  DayView,
  Exclusion,
  ProjectSlice,
  Recap,
  Rule,
  Setting,
  TimelineRun,
  TimelineSegment,
  TimelineView,
  WatcherStatus,
  WeekView,
} from '../bindings';

/** Unwrap a generated `Result`, throwing a readable `Error` on the typed failure. */
function unwrap<T>(r: Result<T, AppError>): T {
  if (r.status === 'error') {
    const e = r.error;
    throw new Error('message' in e ? `${e.kind}: ${e.message}` : e.kind);
  }
  return r.data;
}

/**
 * Fetch activity logs from the backend for a given time range.
 *
 * @param startTime - Unix timestamp for range start
 * @param endTime - Unix timestamp for range end
 * @returns Array of activity logs
 */
export async function getActivityStats(
  startTime: number,
  endTime: number
): Promise<ActivityLog[]> {
  return unwrap(await commands.getActivityStats(startTime, endTime));
}

/**
 * Fetch the computed Day view (context aggregates + context-runs + recap) for a
 * Unix-second range. All numbers are computed in Rust (hard rule 6).
 */
export async function getDay(startTime: number, endTime: number): Promise<DayView> {
  return unwrap(await commands.getDay(startTime, endTime));
}

/**
 * Fetch the computed Week view: 7 day-slices (mini-dial runs + per-day totals) plus
 * week-level aggregates. `dayStarts` are the 7 local midnights (Unix secs); `weekEnd` is
 * the exclusive end of the last day. All numbers are computed in Rust (hard rule 6).
 */
export async function getWeek(dayStarts: number[], weekEnd: number): Promise<WeekView> {
  return unwrap(await commands.getWeek(dayStarts, weekEnd));
}

/**
 * Fetch the computed Timeline view: the day's context-runs, each with its inner app-switch
 * segments (the click-to-expand detail). Numbers are computed in Rust (hard rule 6).
 */
export async function getTimeline(startTime: number, endTime: number): Promise<TimelineView> {
  return unwrap(await commands.getTimeline(startTime, endTime));
}

// --- Contexts (the `categories` table; IPC noun is "context", D31) ---

export async function getContexts(): Promise<Context[]> {
  return unwrap(await commands.getContexts());
}

export async function createContext(name: string, color: string): Promise<number> {
  return unwrap(await commands.createContext(name, color));
}

export async function updateContext(id: number, name: string, color: string): Promise<void> {
  unwrap(await commands.updateContext(id, name, color));
}

export async function deleteContext(id: number): Promise<void> {
  unwrap(await commands.deleteContext(id));
}

// --- Rules ---

export async function getRules(): Promise<Rule[]> {
  return unwrap(await commands.getRules());
}

export async function createRule(
  contextId: number,
  matchField: string,
  pattern: string,
  ignoreTitle: boolean = false,
): Promise<number> {
  return unwrap(await commands.createRule(contextId, matchField, pattern, ignoreTitle));
}

export async function deleteRule(id: number): Promise<void> {
  unwrap(await commands.deleteRule(id));
}

export async function reprocessLogs(): Promise<void> {
  unwrap(await commands.reprocessLogs());
}

// --- Exclusions (D8) ---

export async function getExclusions(): Promise<Exclusion[]> {
  return unwrap(await commands.getExclusions());
}

export async function createExclusion(
  matchType: string,
  pattern: string,
  mode: string,
): Promise<number> {
  return unwrap(await commands.createExclusion(matchType, pattern, mode));
}

export async function deleteExclusion(id: number): Promise<void> {
  unwrap(await commands.deleteExclusion(id));
}

// --- Watcher Status ---

export async function getWatcherStatus(): Promise<WatcherStatus> {
  return unwrap(await commands.getWatcherStatus());
}

// --- Settings ---

export async function getSettings(): Promise<Setting[]> {
  return unwrap(await commands.getSettings());
}

export async function updateSetting(key: string, value: string): Promise<void> {
  unwrap(await commands.updateSetting(key, value));
}

/** Persist the retention window and prune older rows now. Returns rows deleted. `0` = keep forever. */
export async function setRetentionDays(days: number): Promise<number> {
  return unwrap(await commands.setRetentionDays(days));
}

// --- Data ownership ---

/** Absolute path to the SQLite file (for revealing it in Finder). */
export async function getDatabasePath(): Promise<string> {
  return unwrap(await commands.getDatabasePath());
}

/** Write all events to a CSV next to the DB; returns its absolute path. */
export async function exportEventsCsv(): Promise<string> {
  return unwrap(await commands.exportEventsCsv());
}

/** Erase the captured record (events + derived projects/sites); preserves config. */
export async function deleteAllData(): Promise<void> {
  unwrap(await commands.deleteAllData());
}
