// Ergonomic wrappers over the GENERATED IPC client (`src/bindings.ts`).
//
// hard rule 2 / D17: types and the client are generated by tauri-specta, never
// hand-written. The generated `commands.*` return a typed `Result<T, AppError>`;
// these thin wrappers unwrap it to the throwing `Promise<T>` contract the UI
// already uses, and re-export the generated types so the rest of the app imports
// them from one place.
import { commands } from '../bindings';
import type {
  ActivityLog,
  AppError,
  Category,
  Result,
  Rule,
  Setting,
  WatcherStatus,
} from '../bindings';

export type { ActivityLog, AppError, Category, Rule, Setting, WatcherStatus } from '../bindings';

/** Unwrap a generated `Result`, throwing a readable `Error` on the typed failure. */
function unwrap<T>(r: Result<T, AppError>): T {
  if (r.status === 'error') {
    const e = r.error;
    throw new Error('message' in e ? `${e.kind}: ${e.message}` : e.kind);
  }
  return r.data;
}

/**
 * Fetch activity logs from the backend for a given time range.
 *
 * @param startTime - Unix timestamp for range start
 * @param endTime - Unix timestamp for range end
 * @returns Array of activity logs
 */
export async function getActivityStats(
  startTime: number,
  endTime: number
): Promise<ActivityLog[]> {
  return unwrap(await commands.getActivityStats(startTime, endTime));
}

// --- Categories ---

export async function getCategories(): Promise<Category[]> {
  return unwrap(await commands.getCategories());
}

export async function createCategory(name: string, color: string): Promise<number> {
  return unwrap(await commands.createCategory(name, color));
}

export async function deleteCategory(id: number): Promise<void> {
  unwrap(await commands.deleteCategory(id));
}

// --- Rules ---

export async function getRules(): Promise<Rule[]> {
  return unwrap(await commands.getRules());
}

export async function createRule(
  categoryId: number,
  matchField: string,
  pattern: string,
  ignoreTitle: boolean = false,
): Promise<number> {
  return unwrap(await commands.createRule(categoryId, matchField, pattern, ignoreTitle));
}

export async function deleteRule(id: number): Promise<void> {
  unwrap(await commands.deleteRule(id));
}

export async function reprocessLogs(): Promise<void> {
  unwrap(await commands.reprocessLogs());
}

// --- Watcher Status ---

export async function getWatcherStatus(): Promise<WatcherStatus> {
  return unwrap(await commands.getWatcherStatus());
}

// --- Settings ---

export async function getSettings(): Promise<Setting[]> {
  return unwrap(await commands.getSettings());
}

export async function updateSetting(key: string, value: string): Promise<void> {
  unwrap(await commands.updateSetting(key, value));
}
