//! The menubar tray icon: the mono Contexts mark with a "now" triangle pointing at the current
//! local hour — a clock, not a stats HUD (vision §menubar). 24 pre-rendered template frames (one
//! per hour, generated by `design/logo/assets/gen-tray-icons.mjs`) are embedded in the binary; the
//! right one is chosen from local time and refreshed on a slow tick. Black template image ⇒ macOS
//! tints it for the light/dark menu bar.

use tauri::image::Image;

/// Hourly frames 00..23 (mono mark + now-triangle), black template PNGs.
const FRAMES: [&[u8]; 24] = [
    include_bytes!("../icons/tray/now-00.png"),
    include_bytes!("../icons/tray/now-01.png"),
    include_bytes!("../icons/tray/now-02.png"),
    include_bytes!("../icons/tray/now-03.png"),
    include_bytes!("../icons/tray/now-04.png"),
    include_bytes!("../icons/tray/now-05.png"),
    include_bytes!("../icons/tray/now-06.png"),
    include_bytes!("../icons/tray/now-07.png"),
    include_bytes!("../icons/tray/now-08.png"),
    include_bytes!("../icons/tray/now-09.png"),
    include_bytes!("../icons/tray/now-10.png"),
    include_bytes!("../icons/tray/now-11.png"),
    include_bytes!("../icons/tray/now-12.png"),
    include_bytes!("../icons/tray/now-13.png"),
    include_bytes!("../icons/tray/now-14.png"),
    include_bytes!("../icons/tray/now-15.png"),
    include_bytes!("../icons/tray/now-16.png"),
    include_bytes!("../icons/tray/now-17.png"),
    include_bytes!("../icons/tray/now-18.png"),
    include_bytes!("../icons/tray/now-19.png"),
    include_bytes!("../icons/tray/now-20.png"),
    include_bytes!("../icons/tray/now-21.png"),
    include_bytes!("../icons/tray/now-22.png"),
    include_bytes!("../icons/tray/now-23.png"),
];

/// Current local hour (0..23). On macOS via libc `localtime_r` (no timezone crate — libc is already
/// linked for `proc_pidinfo`). Any clock error falls back to 0; this only selects an icon frame.
#[cfg(target_os = "macos")]
pub fn local_hour() -> usize {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0) as libc::time_t;
    // SAFETY: `tm` is zero-initialised before the call; `localtime_r` fills it from a valid time_t
    // and returns null only on failure, which we handle by falling back to hour 0.
    let hour = unsafe {
        let mut tm: libc::tm = std::mem::zeroed();
        if libc::localtime_r(&secs, &mut tm).is_null() {
            return 0;
        }
        tm.tm_hour
    };
    hour.rem_euclid(24) as usize
}

/// Non-macOS is not a shipped target (the product is macOS-only); the UTC hour just keeps the CI
/// build compiling and runnable.
#[cfg(not(target_os = "macos"))]
pub fn local_hour() -> usize {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    ((secs / 3600) % 24) as usize
}

/// The template image for a given hour (wraps at 24). `None` only if an embedded PNG fails to
/// decode — never expected, since the frames ship inside the binary.
pub fn frame(hour: usize) -> Option<Image<'static>> {
    Image::from_bytes(FRAMES[hour % 24]).ok()
}

/// The template image for the current local hour.
pub fn current() -> Option<Image<'static>> {
    frame(local_hour())
}
