// @ts-nocheck
// @generated by tauri-specta — DO NOT EDIT. Run `cargo test export_bindings`.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Fetch activity logs for a `[start_time, end_time]` Unix-second range.
 */
async getActivityStats(startTime: number, endTime: number) : Promise<Result<ActivityLog[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_activity_stats", { startTime, endTime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Build the Day view — per-axis category aggregates, category-runs, and the template
 * recap (D34) — for a `[start_time, end_time]` Unix-second range. Numbers are computed
 * in Rust (hard rule 6); the frontend only renders this.
 */
async getDay(startTime: number, endTime: number) : Promise<Result<DayView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_day", { startTime, endTime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Narrate the day's recap for a `[start_time, end_time]` range with the on-device Foundation
 * Models sidecar, falling back to the deterministic template (D48) on any failure (hard rule
 * 6 / C5). Async + lazy by design (D11): `get_day` already returns the instant template
 * recap, so this never blocks the day load — the UI shows the template immediately, then
 * upgrades the recap card in place when this resolves. Numbers are still computed in Rust;
 * the model only phrases them.
 * 
 * Cached (D52): each day is narrated once. The cache key is a content fingerprint of the
 * day's facts, so a frozen past day is an instant hit (no spawn, no battery) and a rule
 * reprocess that changes the facts produces a new key and re-narrates exactly once. Today
 * regenerates as its facts grow (settle-on-open; a manual refresh re-runs it). Only real
 * model recaps are cached — never the template fallback.
 */
async getRecap(startTime: number, endTime: number) : Promise<Result<Recap, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recap", { startTime, endTime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Build the Week view — 7 day-slices (each a mini-dial's runs + totals) plus week-level
 * aggregates (D34, hard rule 6). `day_starts` are the 7 local midnights (DST-correct,
 * computed by the frontend like `get_day`'s bounds); `week_end` is the exclusive end of
 * the last day. Each day's events are read for `[day_start, next_day_start | week_end)`.
 */
async getWeek(dayStarts: number[], weekEnd: number) : Promise<Result<WeekView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_week", { dayStarts, weekEnd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Build the Timeline view — the day's category-runs, each with its inner app-switch
 * segments (D34) — for a `[start_time, end_time]` Unix-second range. Same read-model
 * inputs as `get_day`; numbers in Rust (hard rule 6).
 */
async getTimeline(startTime: number, endTime: number) : Promise<Result<TimelineView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_timeline", { startTime, endTime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCategories() : Promise<Result<Category[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_categories") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCategory(name: string, color: string) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_category", { name, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCategory(id: number, name: string, color: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_category", { id, name, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCategory(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_category", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRules() : Promise<Result<Rule[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_rules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createRule(categoryId: number, matchField: string, pattern: string, ignoreTitle: boolean | null) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_rule", { categoryId, matchField, pattern, ignoreTitle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteRule(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_rule", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reprocessLogs() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reprocess_logs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getExclusions() : Promise<Result<Exclusion[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_exclusions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createExclusion(matchType: string, pattern: string, mode: string) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_exclusion", { matchType, pattern, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteExclusion(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_exclusion", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWatcherStatus() : Promise<Result<WatcherStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_watcher_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<Setting[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSetting(key: string, value: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persist the retention window **and** immediately prune anything older. Distinct from
 * the generic `update_setting` because retention has a side effect (deleting rows) that
 * a plain key/value setter must not carry. `days <= 0` = "keep forever" (a no-op prune).
 * Returns the number of rows deleted so the UI can confirm.
 */
async setRetentionDays(days: number) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_retention_days", { days }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Absolute path to the SQLite file, so the frontend can reveal it in Finder via the
 * `opener` plugin (path resolution lives in Rust — one source of truth).
 */
async getDatabasePath() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_database_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export all events as RFC-4180 CSV to a file next to the DB (an app-owned dir that
 * already exists — no new fs scope), returning its absolute path for the frontend to
 * reveal. SQL + the file write stay in Rust (hard rule 4); nothing leaves the machine.
 */
async exportEventsCsv() : Promise<Result<string, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_events_csv") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Erase the captured record (events + derived projects/sites), preserving the user's
 * configuration (categories, rules, exclusions, settings). One transaction (see `db`).
 */
async deleteAllData() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_all_data") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The installed-app catalog (name + icon data-URI) backing the UI's `AppIcon`. Reads
 * public app bundles and caches 64px PNGs next to the DB (an app-owned dir — no new
 * fs scope, no network; hard rule 1). Read-only; returns an empty list rather than
 * erroring when nothing scans (e.g. on CI Linux), so the UI just shows monograms.
 */
async listInstalledApps() : Promise<Result<InstalledApp[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_installed_apps") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apps with tracked time that match no rule (they roll up as "Uncategorized"), for the
 * Settings list — all-time, ranked, trivial spans floored (see `db`). Numbers in Rust.
 */
async getUncategorizedApps() : Promise<Result<UncategorizedApp[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_uncategorized_apps") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Snapshot the two macOS capture permissions (Accessibility + Automation) for onboarding +
 * Settings. Non-macOS builds report accessibility=true / automation=NotApplicable.
 */
async getPermissions() : Promise<Result<Permissions, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_permissions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Prompt for Accessibility and open its System Settings → Privacy pane.
 */
async requestAccessibility() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_accessibility") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Trigger the Automation consent prompt for running browsers and open its Privacy pane. Returns
 * whether a browser was running to prompt, so the UI can guide the "open a browser first" case.
 */
async requestAutomation() : Promise<Result<AutomationRequest, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_automation") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a specific System Settings → Privacy pane (Accessibility or Automation).
 */
async openSettingsPane(pane: SettingsPane) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_settings_pane", { pane }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Show + focus the main window, hiding the glance popover (its "Open UsageOS" affordance).
 */
async showMainWindow() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Quit UsageOS entirely (stops background tracking) — the glance popover's "Quit".
 */
async quitApp() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("quit_app") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The single source of command registration. Both the runtime invoke handler
 * and the generated TS bindings come from this Builder, so they cannot disagree
 * Relaunch the app. Used after the updater downloads + installs a new version so the freshly
 * installed binary takes over. Diverges (`restart` replaces the process), so nothing runs after.
 */
async restartApp() : Promise<void> {
    await TAURI_INVOKE("restart_app");
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Activity log entry representing a time block of app usage.
 * 
 * Conceptually the redesign's "event" (the table rename `activity_logs`→`events`
 * is deferred to the UI rewrite to avoid IPC churn). The enrichment fields
 * (`url`/`site`/`project_id`/`project_abstain_reason`/`is_private`) are written by
 * the capture + enrichment layers (Phase 1.2+); current capture leaves them empty.
 */
export type ActivityLog = { id: number; process_name: string; window_title: string; start_time: number; end_time: number; is_idle: boolean; category_id: number | null; 
/**
 * Browser URL for this span, if any. Omitted for private/incognito (D8).
 */
url: string | null; 
/**
 * Parsed host/site from `url` (e.g. "github.com").
 */
site: string | null; 
/**
 * Resolved project (D30). `None` = unassigned.
 */
project_id: number | null; 
/**
 * Why no project was assigned: `None` when assigned, else "no-signal" |
 * "ambiguous". Phase 2 correlates "ambiguous" spans (never "no-signal").
 */
project_abstain_reason: string | null; 
/**
 * A "private" app (D8): time counts, but title/url are not recorded.
 */
is_private: boolean }
/**
 * Typed error contract for every command (replaces `Result<_, String>`).
 * Crosses to TS as a discriminated union the frontend can `switch` on `kind`.
 */
export type AppError = { kind: "Db"; message: string } | { kind: "LockPoisoned" }
/**
 * Outcome of [`request_automation`], so the UI can guide the one case it can't resolve itself.
 * macOS only adds an app to the Automation list once it sends a real Apple Event to a *running*
 * browser — so if none is running, no prompt can be raised and the UI must say so.
 */
export type AutomationRequest = 
/**
 * A supported browser is running — the consent prompt was raised (or the grant was already
 * decided) and the Automation pane was opened. The UI just re-reads the grant.
 */
"prompted" | 
/**
 * No supported browser is running, so no prompt could be raised. The grant will appear the
 * first time a browser is used while tracking; the UI should tell the user to open one.
 */
"no_browser_running"
/**
 * A category (the redesign's noun for the legacy `categories` table — the SQL table
 * and column names stay `categories`/`category_id` per D31; only the IPC surface is
 * renamed). `slug` carries the canonical identity (`deep`|`research`|`comms`|`breaks`)
 * the UI maps to a colour token `--c-<slug>`; `None` = a user-created category (it
 * supplies its own `color`). Exposing `slug` lets the editor protect the canonical
 * four from deletion and colour their swatches from the theme-aware token.
 */
export type Category = { id: number; slug: string | null; name: string; color: string }
/**
 * A continuous stretch of one category — a dial arc, click-to-inspect.
 */
export type CategoryRun = { category_slug: string; category_name: string; 
/**
 * Hex colour for a user-created category; `None` for canonical / uncategorized.
 */
category_color: string | null; 
/**
 * Span bounds (Unix secs); the arc is drawn start→end.
 */
start: number; end: number; 
/**
 * Active seconds within the run (≤ end−start when small gaps are bridged).
 */
secs: number; projects: ProjectSlice[]; apps: string[] }
/**
 * One category's total share of the active day (the ledger/legend/stats unit).
 */
export type CategorySlice = { slug: string; name: string; secs: number; pct: number; 
/**
 * Hex colour for a user-created category; `None` for canonical (coloured by slug) or
 * uncategorized.
 */
color: string | null }
/**
 * One day's compact summary for the Week view: a mini-dial's arcs plus the two totals
 * the week summary needs. `deep_secs` is carried so "deepest day" is a Rust number (rule 6).
 */
export type DaySlice = { 
/**
 * Local midnight (Unix secs) — the mini-dial's angular origin.
 */
day_start: number; active_secs: number; deep_secs: number; runs: CategoryRun[] }
/**
 * Everything the Day view needs, computed from one day of events.
 */
export type DayView = { active_secs: number; idle_secs: number; categories: CategorySlice[]; runs: CategoryRun[]; recap: Recap }
/**
 * A sensitive-handling rule (D8): match an app/site/title and either drop the
 * event (`mode = "exclude"`) or record time without title/url (`mode = "private"`).
 */
export type Exclusion = { id: number; match_type: string; pattern: string; mode: string; created_at: number }
/**
 * One user-facing application and (best-effort) its icon as a data-URI PNG.
 */
export type InstalledApp = { 
/**
 * Display name — the bundle's file stem (e.g. "Visual Studio Code", "Nudge — …").
 */
name: string; 
/**
 * `data:image/png;base64,…`, or `None` when no icon could be extracted.
 */
icon: string | null; 
/**
 * A canonical category slug suggested from the app's `LSApplicationCategoryType`
 * (D47), or `None` when the type is absent or too ambiguous to map. Used to
 * pre-suggest a category in the Uncategorized list — never to auto-assign.
 */
suggested_slug: string | null }
/**
 * One permission's state. Accessibility is a plain granted/not (`AXIsProcessTrusted`) so it
 * rides as a bool on [`Permissions`]; Automation is per-target and genuinely tri-state.
 */
export type PermissionState = "granted" | "denied" | "not_determined" | 
/**
 * Not a macOS build (Linux CI / dev) — the grant doesn't apply.
 */
"not_applicable"
/**
 * Snapshot of both capture permissions for the UI.
 */
export type Permissions = { accessibility: boolean; automation: PermissionState }
/**
 * A project's share of time *inside* a category-run (shown as a text line, never a bar).
 */
export type ProjectSlice = { name: string; secs: number }
/**
 * The day's recap. `generated_by` is "template" here; the on-device Foundation
 * Models prose (Phase 3) will reuse the same facts behind the `ai` trait.
 */
export type Recap = { text: string; generated_by: string }
export type Rule = { id: number; category_id: number; match_field: string; pattern: string; ignore_title: boolean }
/**
 * One persisted setting key/value (replaces the awkward `[string, string][]`).
 */
export type Setting = { key: string; value: string }
/**
 * Which System Settings → Privacy pane a request should open.
 */
export type SettingsPane = "accessibility" | "automation"
/**
 * A category-run plus its inner app-switch segments — one expandable Timeline row (D34).
 */
export type TimelineRun = { category_slug: string; category_name: string; 
/**
 * Hex colour for a user-created category; `None` for canonical / uncategorized.
 */
category_color: string | null; start: number; end: number; secs: number; projects: ProjectSlice[]; apps: string[]; segments: TimelineSegment[] }
/**
 * One focused-window event inside a category-run — the Timeline's click-to-expand detail.
 */
export type TimelineSegment = { start: number; end: number; app: string; 
/**
 * The segment's own category. After excursion-absorb (D34a) a run may contain an absorbed
 * detour of a *different* category, so each segment carries its own — the expand stays honest.
 */
category_slug: string; category_name: string; 
/**
 * Hex colour for a user-created category segment; `None` for canonical / uncategorized.
 */
category_color: string | null; 
/**
 * Resolved project name, or `None` when none was inferred.
 */
project: string | null; 
/**
 * The focused-window title for this stretch — `None` when empty or blanked for a private
 * window (D8). Shown in the Timeline expand so a non-project stretch still says what it was.
 */
title: string | null; secs: number }
/**
 * Everything the Timeline view needs: the day's category-runs, each with its segments.
 * The "Away" idle gaps and the now-marker are derived on the frontend from run bounds.
 */
export type TimelineView = { runs: TimelineRun[] }
/**
 * An app with tracked time that matches no rule — its `category_id` is NULL, so it
 * rolls up as "Uncategorized" (Other). Surfaced in Settings so the user can sort it
 * into a category. `total_secs`/`last_seen` are all-time (retention-bounded): sorting
 * it once re-sorts every past day it appears on (read-time segmentation, D40).
 */
export type UncategorizedApp = { process_name: string; total_secs: number; last_seen: number }
/**
 * Health of the background capture watcher (replaces an untyped `serde_json::Value`).
 */
export type WatcherStatus = { consecutive_errors: number; healthy: boolean }
/**
 * Everything the Week view needs: 7 day-slices + week-level aggregates (numbers in Rust).
 */
export type WeekView = { days: DaySlice[]; total_active_secs: number; avg_active_secs: number; 
/**
 * Index into `days` of the day with the most Deep-work time, or `None` if there was none.
 */
deepest_day: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
