// @ts-nocheck
// @generated by tauri-specta — DO NOT EDIT. Run `cargo test export_bindings`.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Fetch activity logs for a `[start_time, end_time]` Unix-second range.
 */
async getActivityStats(startTime: number, endTime: number) : Promise<Result<ActivityLog[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_activity_stats", { startTime, endTime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Build the Day view — per-axis context aggregates, context-runs, and the template
 * recap (D34) — for a `[start_time, end_time]` Unix-second range. Numbers are computed
 * in Rust (hard rule 6); the frontend only renders this.
 */
async getDay(startTime: number, endTime: number) : Promise<Result<DayView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_day", { startTime, endTime }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Build the Week view — 7 day-slices (each a mini-dial's runs + totals) plus week-level
 * aggregates (D34, hard rule 6). `day_starts` are the 7 local midnights (DST-correct,
 * computed by the frontend like `get_day`'s bounds); `week_end` is the exclusive end of
 * the last day. Each day's events are read for `[day_start, next_day_start | week_end)`.
 */
async getWeek(dayStarts: number[], weekEnd: number) : Promise<Result<WeekView, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_week", { dayStarts, weekEnd }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCategories() : Promise<Result<Category[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_categories") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCategory(name: string, color: string) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_category", { name, color }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteCategory(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_category", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRules() : Promise<Result<Rule[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_rules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createRule(categoryId: number, matchField: string, pattern: string, ignoreTitle: boolean | null) : Promise<Result<number, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_rule", { categoryId, matchField, pattern, ignoreTitle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteRule(id: number) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_rule", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reprocessLogs() : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reprocess_logs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWatcherStatus() : Promise<Result<WatcherStatus, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_watcher_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<Setting[], AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSetting(key: string, value: string) : Promise<Result<null, AppError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Activity log entry representing a time block of app usage.
 * 
 * Conceptually the redesign's "event" (the table rename `activity_logs`→`events`
 * is deferred to the UI rewrite to avoid IPC churn). The enrichment fields
 * (`url`/`site`/`project_id`/`project_abstain_reason`/`is_private`) are written by
 * the capture + enrichment layers (Phase 1.2+); current capture leaves them empty.
 */
export type ActivityLog = { id: number; process_name: string; window_title: string; start_time: number; end_time: number; is_idle: boolean; category_id: number | null; 
/**
 * Browser URL for this span, if any. Omitted for private/incognito (D8).
 */
url: string | null; 
/**
 * Parsed host/site from `url` (e.g. "github.com").
 */
site: string | null; 
/**
 * Resolved project (D30). `None` = unassigned.
 */
project_id: number | null; 
/**
 * Why no project was assigned: `None` when assigned, else "no-signal" |
 * "ambiguous". Phase 2 correlates "ambiguous" spans (never "no-signal").
 */
project_abstain_reason: string | null; 
/**
 * A "private" app (D8): time counts, but title/url are not recorded.
 */
is_private: boolean }
/**
 * Typed error contract for every command (replaces `Result<_, String>`).
 * Crosses to TS as a discriminated union the frontend can `switch` on `kind`.
 */
export type AppError = { kind: "Db"; message: string } | { kind: "LockPoisoned" }
export type Category = { id: number; name: string; color: string }
/**
 * A continuous stretch of one context — a dial arc, click-to-inspect.
 */
export type ContextRun = { context_slug: string; context_name: string; 
/**
 * Span bounds (Unix secs); the arc is drawn start→end.
 */
start: number; end: number; 
/**
 * Active seconds within the run (≤ end−start when small gaps are bridged).
 */
secs: number; projects: ProjectSlice[]; apps: string[] }
/**
 * One context's total share of the active day (the ledger/legend/stats unit).
 */
export type ContextSlice = { slug: string; name: string; secs: number; pct: number }
/**
 * One day's compact summary for the Week view: a mini-dial's arcs plus the two totals
 * the week summary needs. `deep_secs` is carried so "deepest day" is a Rust number (rule 6).
 */
export type DaySlice = { 
/**
 * Local midnight (Unix secs) — the mini-dial's angular origin.
 */
day_start: number; active_secs: number; deep_secs: number; runs: ContextRun[] }
/**
 * Everything the Day view needs, computed from one day of events.
 */
export type DayView = { active_secs: number; idle_secs: number; contexts: ContextSlice[]; runs: ContextRun[]; recap: Recap }
/**
 * A project's share of time *inside* a context-run (shown as a text line, never a bar).
 */
export type ProjectSlice = { name: string; secs: number }
/**
 * The day's recap. `generated_by` is "template" here; the on-device Foundation
 * Models prose (Phase 3) will reuse the same facts behind the `ai` trait.
 */
export type Recap = { text: string; generated_by: string }
export type Rule = { id: number; category_id: number; match_field: string; pattern: string; ignore_title: boolean }
/**
 * One persisted setting key/value (replaces the awkward `[string, string][]`).
 */
export type Setting = { key: string; value: string }
/**
 * Health of the background capture watcher (replaces an untyped `serde_json::Value`).
 */
export type WatcherStatus = { consecutive_errors: number; healthy: boolean }
/**
 * Everything the Week view needs: 7 day-slices + week-level aggregates (numbers in Rust).
 */
export type WeekView = { days: DaySlice[]; total_active_secs: number; avg_active_secs: number; 
/**
 * Index into `days` of the day with the most Deep-work time, or `None` if there was none.
 */
deepest_day: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
